//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Social/Members/Ryan/Ryan_Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Ryan
{
    public partial class @Ryan_Input: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Ryan_Input()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Ryan_Input"",
    ""maps"": [
        {
            ""name"": ""FarmingInSpace"",
            ""id"": ""201cfe93-547b-4053-9263-cddd8f6711f1"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""065d8930-1901-491f-b885-9ba61254b364"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""db01af7f-1ce6-4d97-8579-ef67aaf1c624"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // FarmingInSpace
            m_FarmingInSpace = asset.FindActionMap("FarmingInSpace", throwIfNotFound: true);
            m_FarmingInSpace_Interact = m_FarmingInSpace.FindAction("Interact", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // FarmingInSpace
        private readonly InputActionMap m_FarmingInSpace;
        private List<IFarmingInSpaceActions> m_FarmingInSpaceActionsCallbackInterfaces = new List<IFarmingInSpaceActions>();
        private readonly InputAction m_FarmingInSpace_Interact;
        public struct FarmingInSpaceActions
        {
            private @Ryan_Input m_Wrapper;
            public FarmingInSpaceActions(@Ryan_Input wrapper) { m_Wrapper = wrapper; }
            public InputAction @Interact => m_Wrapper.m_FarmingInSpace_Interact;
            public InputActionMap Get() { return m_Wrapper.m_FarmingInSpace; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FarmingInSpaceActions set) { return set.Get(); }
            public void AddCallbacks(IFarmingInSpaceActions instance)
            {
                if (instance == null || m_Wrapper.m_FarmingInSpaceActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_FarmingInSpaceActionsCallbackInterfaces.Add(instance);
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }

            private void UnregisterCallbacks(IFarmingInSpaceActions instance)
            {
                @Interact.started -= instance.OnInteract;
                @Interact.performed -= instance.OnInteract;
                @Interact.canceled -= instance.OnInteract;
            }

            public void RemoveCallbacks(IFarmingInSpaceActions instance)
            {
                if (m_Wrapper.m_FarmingInSpaceActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IFarmingInSpaceActions instance)
            {
                foreach (var item in m_Wrapper.m_FarmingInSpaceActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_FarmingInSpaceActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public FarmingInSpaceActions @FarmingInSpace => new FarmingInSpaceActions(this);
        public interface IFarmingInSpaceActions
        {
            void OnInteract(InputAction.CallbackContext context);
        }
    }
}
