//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/RGD_Core/Input/RGD_Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RGD_Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RGD_Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RGD_Controls"",
    ""maps"": [
        {
            ""name"": ""DefaultMapping"",
            ""id"": ""1665f2bd-b0f0-4af7-9bb5-cc24f882ad65"",
            ""actions"": [
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""ab5709bb-ba09-466d-a7cf-bf378cd7759b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9238b264-e3ab-454c-90bb-25286b2a0052"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultMapping
        m_DefaultMapping = asset.FindActionMap("DefaultMapping", throwIfNotFound: true);
        m_DefaultMapping_Space = m_DefaultMapping.FindAction("Space", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultMapping
    private readonly InputActionMap m_DefaultMapping;
    private List<IDefaultMappingActions> m_DefaultMappingActionsCallbackInterfaces = new List<IDefaultMappingActions>();
    private readonly InputAction m_DefaultMapping_Space;
    public struct DefaultMappingActions
    {
        private @RGD_Controls m_Wrapper;
        public DefaultMappingActions(@RGD_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Space => m_Wrapper.m_DefaultMapping_Space;
        public InputActionMap Get() { return m_Wrapper.m_DefaultMapping; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultMappingActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultMappingActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultMappingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultMappingActionsCallbackInterfaces.Add(instance);
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
        }

        private void UnregisterCallbacks(IDefaultMappingActions instance)
        {
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
        }

        public void RemoveCallbacks(IDefaultMappingActions instance)
        {
            if (m_Wrapper.m_DefaultMappingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultMappingActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultMappingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultMappingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultMappingActions @DefaultMapping => new DefaultMappingActions(this);
    public interface IDefaultMappingActions
    {
        void OnSpace(InputAction.CallbackContext context);
    }
}
